network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 192.168.20.132/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.20.2
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

